### PR TITLE
Spinner code Added

### PR DESCRIPTION
**Pull request by sumateja**
Have Added spinner code examples

### CODE REVIEW

**Comment by sumateja** [comment]
Please help me i checked in files & submitted a merge request then closed the pull request but changes are not visible in master main branch. I did something wrong

**Comment by Caleb335** [comment]
Why did you close your own PR @sumateja

**Comment by sumateja** [comment]
Sorry I don't know what to do so closed. later I created new fork and again
checked in got some code comments need to correct those ans check in.

**Comment by Caleb335** [comment]
👌

**Pull request closed without merging**
