### PR TITLE
[Issue#38] Setup eslint config for the project Closes #38,#37

### LINKED ISSUE #38: Add eslint for the project
We should add the `eslint` in our project so that the code is clean and properly linted and following the industry standards.

### PR DESCRIPTION
**Pull request by madhuni**
### In this PR

I have set up the `eslint` config for the project and added some basic rules ko make sure the code follows industry standards and best practices. Below are the key changes done as part of this PR:

- I have fixed the linting errors in all the existing components.

- For many of the components, `.js` was used as the file extension and we were using `.css` for some components and `.scss` for some components. I have made sure that all the files which includes `jsx` syntax, are renamed with `.jsx` extension and all the `.css` files are renamed as `.scss`.

- I have also made sure that the file name of the `.scss` the file is `pascalCase` e.g. `SimpleButton.scss` and not `simpleButton.scss`. For the upcoming PR's we should make sure that the component files are being generated via `plop` templates using the `gen:c` script so that these issues won't happen.

- I have also added the `pre-commit` and `pre-push` hooks. This is going to make sure that the code is properly formatted and linted before the user is allowed to make any commit or push to the remote repository.

### CODE REVIEW

**Comment by madhuni** [comment]
@NehemiahK, @KrishnaMoorthy12, @Caleb335 since we are having a couple of open PRs, let's make sure that this PR is reviewed and merged first so that the other contributors can take a pull from `master` and install the linting rules and fix them so that we don't find any of these errors in the existing PR(s).

**Comment by Caleb335** [comment]
Awesome work @madhuni 🙌 I like the way you documented your PR.

BTW @NehemiahK  I'm thinking we should have a way to communicate with the people who are contributing to this repository of some changes that would be or are necessary for development, for example, a case like this now, we'd have explained to them the new updates to the repository and how they can go about contributing effectively.

What do you guys think

**Comment by NehemiahK** [comment]
@Caleb335 what did you have in mind? Also Thanks @madhuni this seems awesome

**Comment by madhuni** [comment]
Thanks @Caleb335, @NehemiahK.

>BTW @NehemiahK I'm thinking we should have a way to communicate with the people who are contributing to this repository of some changes that would be or are necessary for development, for example, a case like this now, we'd have explained to them the new updates to the repository and how they can go about contributing effectively.
>What do you guys think

Regarding this, I think that's a good point @Caleb335. I also feel the need to communicate different things but every time creating a new issue doesn't make sense.

What about having a **discord server** for our project? We can have all the contributors in one place, and we can share all the updates as announcements. Also, we can have multiple channels to talk about different things. WDYT?

**Comment by NehemiahK** [comment]
The issue is I think there are generally two types of contributors. Those who are very active and will read updates/etc if it's on Discord or Github. But, the majority of contributors are one-time contributors, so they will be unlikely to join a Discord for example

**Comment by NehemiahK** [comment]
Makes sense. 

- I agree the CI/CD you mentioned could be really useful.
- No issue with the Discord server as long as we are aware most people contributing will not be using it.

**Comment by Caleb335** [comment]
> Your point is valid. I have two points for that:
> 
> 1- We have to make sure the contribution guide is up to date and additionally we can add some automated tasks in our workflow which will make sure that any PR or an issue is following the standards or not.
> 
> 2- Having a separate discord server will not cause any harm to us. At least the active contributors will have a common place to discuss things on how to take things further in the future. We will know each other as well and if other contributors want, they can also keep in touch with the team.
> 
> Let me know your thoughts.

This is ok, automating the process would make us informed of some certain changes.

So what aspects are tracking...

"When issues are submitted or when PRs are submitted to be merged"?

**Comment by Caleb335** [comment]
> @Caleb335 what did you have in mind? Also Thanks @madhuni this seems awesome

Let's go with @madhuni idea

**Comment by madhuni** [comment]
> So what aspects are tracking...

> "When issues are submitted or when PRs are submitted to be merged"?

We will include both of them. We will provide the contributors to follow a certain template while raising a PR or creating a new issue. I will take this up as part of #50. @NehemiahK can you please assign this issue to me?

Also, I have one question, @NehemiahK what are the parameters to fulfill in order to get access to merge the PR(s) and assigning issues. I am frequently reviewing the PR so sometimes feels if I can get permission to merge the PR(s). Just wanted to quickly check on this.

**Comment by ashispavan** [comment]
@NehemiahK , @madhuni , @Caleb335 I have taken the liberty to create a Discord server. Please feel free to join: 

https://discord.gg/CGT8TCx

@NehemiahK I agree to your point that one-time contributors won't be using it. Nevertheless, we could use it for this and for any other open-source projects or discussions. I believe it would be a good place to find and share other projects that we can contribute/learn.

**Comment by kaf-lamed-beyt** [comment]
Nice work 👍

**Pull request merged**
